#ifndef SECC_STATE_H
#define SECC_STATE_H

typedef enum {
    SECC_STATE_IDLE = 0,
    /* SLAC phase (Power Line Communication) */
    SECC_STATE_SLAC_INIT,
    SECC_STATE_SLAC_MATCHING,
    SECC_STATE_SLAC_MATCHED,
    /* TLS/TCP phase (over Power Line) */
    SECC_STATE_TCP_CONNECTED,
    SECC_STATE_TLS_HANDSHAKE,
    SECC_STATE_SESSION_SETUP,
    SECC_STATE_SERVICE_DISCOVERY,
    SECC_STATE_PAYMENT_SELECTION,
    SECC_STATE_AUTHORIZATION,
    SECC_STATE_CHARGE_PARAMETER,
    SECC_STATE_CABLE_CHECK,
    SECC_STATE_PRECHARGE,
    SECC_STATE_POWER_DELIVERY,
    SECC_STATE_CURRENT_DEMAND,
    SECC_STATE_WELDING_DETECTION,
    SECC_STATE_SESSION_STOP,
    SECC_STATE_ERROR
} secc_state_t;

#endif